// tslint:disable
/**
 * !!GENERATED FILE!!
 *
 * WARNING:  Do not edit this file, changes will be overwritten.
 *
 * Classificationbox
 * ClassificationBox API descriptors (unofficial)
 *
 * @mbx/api-classificationbox v1.0.0
 */

export * from './api';
export * from './configuration';
