// tslint:disable
/**
 * !!GENERATED FILE!!
 *
 * WARNING:  Do not edit this file, changes will be overwritten.
 *
 * Tagbox API
 * Tagbox API descriptors (unofficial)
 *
 * OpenAPI spec version: 1.0.1
 */

export * from './api';
export * from './configuration';
